const ProductList = [
  {
    id: 1,
    img: "https://images.mamaearth.in/catalog/product/r/i/rice-fw-1.jpg?format=auto&width=400&height=400",
    rating: "4.5 / 25",
    title: "Hydrating Face Serum",
    product_volume: "30ml",
    price: "NPR 2,500",
    description: "Deeply hydrates and nourishes your skin for a glowing look.",
  },
  {
    id: 2,
    img: "https://images.mamaearth.in/catalog/product/r/i/rice-fw-1.jpg?format=auto&width=400&height=400",
    rating: 4.2,
    title: "Vitamin C Brightening Cream",
    product_volume: "50g",
    price: "NPR 1,800",
    description: "Reduces dark spots and enhances skin radiance.",
  },
  {
    id: 3,
    img: "https://images.mamaearth.in/catalog/product/r/i/rice-fw-1.jpg?format=auto&width=400&height=400",
    rating: 4.8,
    title: "Aloe Vera Gel",
    product_volume: "100ml",
    price: "NPR 700",
    description: "Soothes and moisturizes sensitive skin.",
  },
  {
    id: 4,
    img: "https://images.mamaearth.in/catalog/product/r/i/rice-fw-1.jpg?format=auto&width=400&height=400",
    rating: 4.1,
    title: "Sunscreen SPF 50",
    product_volume: "75ml",
    price: "NPR 1,500",
    description: "Protects skin from harmful UV rays and prevents sun damage.",
  },
  {
    id: 5,
    img: "https://images.mamaearth.in/catalog/product/r/i/rice-fw-1.jpg?format=auto&width=400&height=400",
    rating: 4.6,
    title: "Charcoal Face Wash",
    product_volume: "150ml",
    price: "NPR 850",
    description: "Removes dirt and excess oil for a fresh and clear face.",
  },
  {
    id: 6,
    img: "https://images.mamaearth.in/catalog/product/r/i/rice-fw-1.jpg?format=auto&width=400&height=400",
    rating: 4.3,
    title: "Night Repair Cream",
    product_volume: "50g",
    price: "NPR 2,200",
    description: "Repairs and rejuvenates skin overnight for a youthful glow.",
  },
  {
    id: 7,
    img: "https://images.mamaearth.in/catalog/product/r/i/rice-fw-1.jpg?format=auto&width=400&height=400",
    rating: 4.7,
    title: "Hyaluronic Acid Moisturizer",
    product_volume: "60ml",
    price: "NPR 2,000",
    description: "Locks in moisture and keeps skin plump and hydrated.",
  },
  {
    id: 8,
    img: "https://images.mamaearth.in/catalog/product/r/i/rice-fw-1.jpg?format=auto&width=400&height=400",
    rating: 4.0,
    title: "Rose Water Toner",
    product_volume: "120ml",
    price: "NPR 950",
    description: "Refreshes and tones skin while maintaining pH balance.",
  },
  {
    id: 9,
    img: "https://images.mamaearth.in/catalog/product/r/i/rice-fw-1.jpg?format=auto&width=400&height=400",
    rating: 4.9,
    title: "Anti-Aging Retinol Serum",
    product_volume: "30ml",
    price: "NPR 3,000",
    description: "Reduces wrinkles and fine lines for a youthful appearance.",
  },
  {
    id: 10,
    img: "https://images.mamaearth.in/catalog/product/r/i/rice-fw-1.jpg?format=auto&width=400&height=400",
    rating: 4.4,
    title: "Exfoliating Face Scrub",
    product_volume: "100g",
    price: "NPR 1,200",
    description: "Gently exfoliates dead skin cells and unclogs pores.",
  },
];

export default ProductList;
