const HairProduct = [
  {
    id: 1,
    img: "https://images.mamaearth.in/catalog/product/o/n/onion-hair-oil-1.jpg?format=auto&width=400&height=400",
    rating: "4.5 / 25",
    title: "Onion Hair Oil",
    product_volume: "150ml",
    price: "NPR 1,200",
    description: "Boosts hair growth and reduces hair fall with onion oil.",
  },
  {
    id: 2,
    img: "https://images.mamaearth.in/catalog/product/r/i/rice-hair-mask-1.jpg?format=auto&width=400&height=400",
    rating: 4.2,
    title: "Rice Water Hair Mask",
    product_volume: "200ml",
    price: "NPR 1,500",
    description:
      "Strengthens and repairs damaged hair with fermented rice water.",
  },
  {
    id: 3,
    img: "https://images.mamaearth.in/catalog/product/a/r/argan-shampoo-1.jpg?format=auto&width=400&height=400",
    rating: 4.8,
    title: "Argan Shampoo",
    product_volume: "250ml",
    price: "NPR 1,100",
    description: "Moisturizes and nourishes hair with argan oil and keratin.",
  },
  {
    id: 4,
    img: "https://images.mamaearth.in/catalog/product/b/r/bhringraj-hair-oil-1.jpg?format=auto&width=400&height=400",
    rating: 4.6,
    title: "Bhringraj Hair Oil",
    product_volume: "200ml",
    price: "NPR 1,400",
    description: "Improves scalp health and promotes thicker hair growth.",
  },
  {
    id: 5,
    img: "https://images.mamaearth.in/catalog/product/m/i/mint-shampoo-1.jpg?format=auto&width=400&height=400",
    rating: 4.4,
    title: "Tea Tree & Mint Shampoo",
    product_volume: "300ml",
    price: "NPR 1,300",
    description: "Soothes itchy scalp and removes dandruff effectively.",
  },
  {
    id: 6,
    img: "https://images.mamaearth.in/catalog/product/a/m/amla-hair-mask-1.jpg?format=auto&width=400&height=400",
    rating: 4.7,
    title: "Amla & Bhringraj Hair Mask",
    product_volume: "200ml",
    price: "NPR 1,600",
    description: "Repairs dry and damaged hair for a silky smooth texture.",
  },
  {
    id: 7,
    img: "https://images.mamaearth.in/catalog/product/c/o/conditioner-1.jpg?format=auto&width=400&height=400",
    rating: 4.5,
    title: "Keratin Conditioner",
    product_volume: "250ml",
    price: "NPR 1,200",
    description: "Provides deep nourishment and restores hair shine.",
  },
  {
    id: 8,
    img: "https://images.mamaearth.in/catalog/product/h/a/hair-serum-1.jpg?format=auto&width=400&height=400",
    rating: 4.9,
    title: "Hair Strengthening Serum",
    product_volume: "50ml",
    price: "NPR 2,000",
    description: "Reduces frizz and strengthens hair strands.",
  },
  {
    id: 9,
    img: "https://images.mamaearth.in/catalog/product/l/e/leave-in-conditioner-1.jpg?format=auto&width=400&height=400",
    rating: 4.3,
    title: "Leave-In Conditioner",
    product_volume: "150ml",
    price: "NPR 1,500",
    description: "Detangles and softens hair without weighing it down.",
  },
  {
    id: 10,
    img: "https://images.mamaearth.in/catalog/product/h/a/hair-growth-tonic-1.jpg?format=auto&width=400&height=400",
    rating: 4.8,
    title: "Hair Growth Tonic",
    product_volume: "100ml",
    price: "NPR 1,800",
    description: "Promotes healthy hair growth with biotin and caffeine.",
  },
];

export default HairProduct;
